// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Takoni",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Widget Script */}
        <script
          src="http://localhost:3000/borneo-sentra-digital/alex/widget.js"
          async
        ></script>

        {children}
      </body>
    </html>
  );
}
